Holiday Package Prediciton

Problem Statement: "Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base.
One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information.
The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.
However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
df=pd.read_csv("Travel.csv")

In [4]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

Data Cleaning

In [7]:
df.isnull().sum() #got the total no. of null values in the categories

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [17]:
df.describe

<bound method NDFrame.describe of       CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   NaN     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]>

In [22]:
df['Gender'].value_counts() #here there is an mistake in the spelling of female

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [21]:
df['MaritalStatus'].value_counts() #here single and unmarried is same

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [23]:
df['TypeofContact'].value_counts() #this one is ok

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [26]:
df['Gender'] = df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [27]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [28]:
df.head(
    
)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0